# Generated by Django 3.0.7 on 2020-07-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200630_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
